import { TabWidget, HorizontalBox } from "std-widgets.slint";
import { Logic, InstanceS, LoaderS } from "../logic.slint";

export component SelectInstanceButton {
    in-out property <InstanceS> instance;

    function loader-to-string() -> string {
        if instance.loader == LoaderS.Vanilla {
            "Vanilla"
        } else if instance.loader == LoaderS.Fabric {
            "Fabric"
        } else if instance.loader == LoaderS.Optifine {
            "Optifine"
        } else if instance.loader == LoaderS.NeoForge {
            "NeoForge"
        } else if instance.loader == LoaderS.Quilt {
            "Quilt"
        } else {
            "Vanilla"
        }
    }
    
    Rectangle {
        border-color: aliceblue;
        border-width: 0.8px;
        border-radius: 7px;

        HorizontalBox {
            vertical-stretch: 1.0;
            horizontal-stretch: 1.0;
            alignment: LayoutAlignment.center;

            Text {
                text: instance.name + "\n" + "Version: " +  instance.version + "\n" + "Loader: " + loader-to-string();
                font-size: 18px;
                horizontal-alignment: TextHorizontalAlignment.center;
            }
        }

        TouchArea {
            clicked => {
                Logic.run-instance(instance.name);
                instance.is-run = instance.is-run ? false : true;
            }
        }
    }
}
