import { Logic, Page } from "../logic.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export component TopBar inherits VerticalLayout {
    height: 40px;

    HorizontalLayout {
        HorizontalBox {
            width: 100px;
            Button {
                text: Logic.current-account.name;
                height: 30px;
                clicked => {
                    Logic.current-page = Page.Login;
                }
            }
        }
    }

    Rectangle {
        height: 0.7px;
        background: white;
    }
}
