import { Button, VerticalBox, ProgressIndicator } from "std-widgets.slint";
import { SelectInstancePage } from "select-instance.slint";
import { Logic, InstanceS } from "Logic.slint"; export { Logic, InstanceS}


export component AppWindow inherits Window {
    preferred-width: 100px;
    preferred-height: 800px;
    min-width: 100px;
    min-height: 800px;

    HorizontalLayout {
        SelectInstancePage { }
        VerticalLayout { }
    }
}
