import {
    Button,
    VerticalBox,
    ProgressIndicator,
    HorizontalBox,
} from "std-widgets.slint";
import { SelectInstance } from "select-instance.slint";
import { Logic, InstanceS, LoaderS, AccountSelectedS, Page, AccountS } from "logic.slint"; export { Logic, InstanceS, LoaderS, AccountSelectedS, AccountS }
import { CreateInstance } from "create-instance.slint";
import { LoginPage } from "login.slint";
import { TopBar } from "components/top-bar.slint";


export component AppWindow inherits Window {
    preferred-width: 1000px;
    preferred-height: 800px;
    min-width: 1000px;
    min-height: 800px;

    VerticalLayout {

        if Logic.current-page != Page.Login: TopBar { }

        if Logic.current-page == Page.Login: LoginPage {
            alignment: LayoutAlignment.center;
        }

        if Logic.current-page == Page.CreateInstance: HorizontalBox {
            SelectInstance { }

            CreateInstance { }
        }
    }
}
