import { LoaderS, Logic, InstanceS } from "Logic.slint";
import { ComboBox, Button, TextEdit, HorizontalBox, LineEdit, VerticalBox } from "std-widgets.slint";

export struct MinecraftVersion {
    
}

export component CreateInstance {
    in-out property <InstanceS> instance;
    in-out property <[string]> minecraft-versions: [
        "26.1",
        "1.21.11",
        "1.21.10",
        "1.21.9",
        "1.21.8",
        "1.21.7",
        "1.21.6",
        "1.21.5",
        "1.21.4",
        "1.21.3",
        "1.21.2",
        "1.21.1",
        "1.21"
    ];


    function loader-to-string(loader: LoaderS) -> string {
        if loader == LoaderS.Vanilla {
            "Vanilla"
        } else if loader == LoaderS.Fabric {
            "Fabric"
        } else if loader == LoaderS.Forge {
            "Forge"
        } else if loader == LoaderS.Optifine {
            "Optifine"
        } else if loader == LoaderS.NeoForge {
            "NeoForge"
        } else if loader == LoaderS.Quilt {
            "Quilt"
        } else {
            "Vanilla"
        }
    }

    function loader-to-enum(loader: string) -> LoaderS {
        if loader == "Vanilla" {
            LoaderS.Vanilla
        } else if loader == "Fabric" {
            LoaderS.Fabric
        } else if loader == "Forge" {
            LoaderS.Forge
        } else if loader == "Optifine" {
            LoaderS.Optifine
        } else if loader == "NeoForge" {
            LoaderS.NeoForge
        } else if loader == "Quilt" {
            LoaderS.Quilt
        } else {
            LoaderS.Vanilla
        }
    }

    VerticalBox {
        alignment: LayoutAlignment.center;
        
        LineEdit {
            height: 30px;
            placeholder-text: "Instance Name";
            text: instance.name;
            edited(text) => {
                instance.name = text;
            }
        }
        
        ComboBox {
            model: minecraft-versions;
            selected(current-value) => {
                instance.version = current-value;
            }
        }

        ComboBox {
            model: [
                loader-to-string(LoaderS.Vanilla),
                loader-to-string(LoaderS.Fabric),
                loader-to-string(LoaderS.Forge),
                loader-to-string(LoaderS.Optifine),
                loader-to-string(LoaderS.NeoForge),
                loader-to-string(LoaderS.Quilt)
            ];
            selected(current-value) => {
                instance.loader = loader-to-enum(current-value);
            }
        }

        if instance.loader != LoaderS.Vanilla: LineEdit {
            height: 30px;
            placeholder-text: "Loader Version";
            text: instance.loader-version;
            edited(text) => {
                instance.loader-version = text;
            }
        }

        Button {
            height: 30px;
            text: "Create Instance";
            clicked => {
                Logic.create-instance(instance);
            } 
        }
        
    }
}
