export enum LoaderS {Vanilla, Fabric, Forge, Optifine, NeoForge, Quilt}
export enum Login {Offline, Online}
export enum Page {CreateInstance, EditInstance, Login}
export enum AccountSelectedS { Online, Offline }


export struct AccountS {
    name: string,
    mode: string
}

export struct InstanceS {
    name: string,
    version: string,
    loader-version: string,
    loader: LoaderS,
    is_run: bool
}

export global Logic {
    in-out property <Page> current-page: Page.Login;
    in-out property <AccountSelectedS> Account-mod-selected;
    in-out property <[InstanceS]> instances;
    in-out property <AccountS> current-profile;
    in-out property <[AccountS]> accounts;

    callback create-instance(InstanceS);
    callback run-instance(name: string);

    // login online 
    callback login-online-account(AccountS);

    // create offline account
    callback create-offline-account(AccountS) -> bool;
    callback login-offline-account(AccountS);
}

