export enum LoaderS {Vanilla, Fabric, Forge, Optifine, NeoForge, Quilt}
export enum Login {Offline, Online}
export enum Page {CreateInstance, PlayInstance, Login}
export enum ProfileSelectedS { Online, Offline }


export struct CurrentProfile {
    
}

export struct InstanceS {
    name: string,
    version: string,
    loader-version: string,
    loader: LoaderS,
    is_run: bool
}

export global Logic {
    in-out property <ProfileSelectedS> profile-mod-selected;
    in property <string> offline_profile_name;
    in-out property <[InstanceS]> instances;
    in-out property <Page> current-page;


    callback create-instance(InstanceS);
    callback run-instance(name: string);
}
