import {
    Button,
    VerticalBox,
    LineEdit,
    ComboBox,
    ListView,
    HorizontalBox,
    GridBox,
} from "std-widgets.slint";
import { Logic, AccountS } from "logic.slint";

export global LoginLogic {
    in-out property <AccountS> new-account;
    in-out property <bool> is-select-mode: true;

    public pure function check_number_accounts() -> bool {
        if Logic.accounts.length >= 1 {
            true
        } else { false }
    }
}


export component AccountList inherits HorizontalBox {
    alignment: LayoutAlignment.center;

    VerticalLayout {
        alignment: LayoutAlignment.center;
        Text {
            text: "Accounts";
            font-size: 20px;
            horizontal-alignment: TextHorizontalAlignment.center;
        }

        ListView {
            width: 200px;
            height: 300px;
            for account in Logic.accounts: HorizontalLayout {
                padding: 4px;
                Button {
                    text: account.name + "\n" + account.mode;
                    clicked => {
                        if account.mode == "Online" {
                            Logic.login-online-account(account)
                        } else {
                            Logic.login-offline-account(account)
                        }
                    }
                }
            }
        }
    }
}

export component SelectAccountLogin inherits VerticalBox {
    alignment: LayoutAlignment.center;

    HorizontalBox {
        alignment: LayoutAlignment.center;

        Rectangle {
            border-color: white;
            border-radius: 7px;
            border-width: 0.7px;

            width: 500px;
            height: 500px;

            VerticalBox {
                HorizontalLayout {
                    height: 30px;
                    alignment: LayoutAlignment.center;
                    padding: 3px;
                    spacing: 10px;
                    Button {
                        text: "Online Auth";
                        height: 30px;
                        width: 150px;
                        clicked => {
                            LoginLogic.new-account.mode = "Online";
                            LoginLogic.new-account.name = "";
                            LoginLogic.is-select-mode = false;
                            Logic.login-online-account(LoginLogic.new-account);
                        }
                    }

                    Button {
                        text: "Offline Auth";
                        height: 30px;
                        width: 150px;
                        clicked => {
                            LoginLogic.new-account.mode = "Offline";
                            LoginLogic.new-account.name = "";
                            LoginLogic.is-select-mode = false;
                        }
                    }
                }

                if LoginLogic.check_number_accounts(): AccountList { }
            }
        }
    }
}

export component CreateOrLoginAccount inherits VerticalBox {
    alignment: LayoutAlignment.center;
    height: 100%;

    HorizontalBox {
        alignment: LayoutAlignment.center;

        Rectangle {
            border-color: white;
            border-radius: 7px;
            border-width: 0.7px;

            width: 500px;
            height: 500px;

            HorizontalLayout {
                alignment: LayoutAlignment.center;

                if LoginLogic.new-account.mode == "Online": VerticalBox {
                    alignment: LayoutAlignment.center;
                    Text {
                        text: "Link www foi aberto no navegador";
                    }
                }

                if LoginLogic.new-account.mode == "Offline": VerticalBox {
                    alignment: LayoutAlignment.center;

                    HorizontalBox {
                        width: 100%;
                        alignment: LayoutAlignment.center;
                        Button {
                            text: "<";
                            clicked => {
                                LoginLogic.is-select-mode = true;
                                LoginLogic.new-account.name = "";
                                LoginLogic.new-account.mode = "";
                            }
                        }

                        line-edit := LineEdit {
                            placeholder-text: "Account Name";
                            width: 300px;
                            edited(name) => {
                                LoginLogic.new-account.name = name;
                            }
                        }
                    }

                    HorizontalLayout {
                        alignment: LayoutAlignment.center;

                        if LoginLogic.new-account.name > 0: Button {
                            text: "Create";
                            width: 200px;
                            clicked => {
                                is-created-text.text = Logic.create-offline-account(LoginLogic.new-account) ? "Account Created" : "The account already exists";
                                line-edit.text = "";
                                LoginLogic.new-account.name = "";
                            }
                        }
                    }

                    is-created-text := Text {
                        horizontal-alignment: TextHorizontalAlignment.center;
                        font-size: 20px;
                    }
                }
            }
        }
    }
}


export component LoginPage inherits VerticalBox {
    if LoginLogic.is-select-mode:SelectAccountLogin { }

    if !LoginLogic.is-select-mode:CreateOrLoginAccount { }
}
