import { ListView } from "std-widgets.slint";
import { SelectInstanceButton } from "components/select-instance-button.slint";
import { Logic } from "logic.slint";
import { CreateInstance } from "create-instance.slint";

export component SelectInstance inherits VerticalLayout {
    Rectangle {
        background: #363636;
        width: 200px;
        ListView {
            height: parent.height;
            for instance in Logic.instances : VerticalLayout {
                padding: 4px;
                SelectInstanceButton {
                    instance: instance;
                }
            }
        }
    }
}